version: '3.4'

services:
  yoctoqueue:
    image: yoctoqueue
    build:
      context: node_modules/yocto-queue
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
